networks:
  services-net:
    driver: bridge

services:

  # MySQL Database
  db:
    image: mysql:9
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - services-net

  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    networks:
      - services-net

  # Backend Symfony
  backend:
    build:
      context: ./docker/php
    image: ecommerce_php:1.0
    container_name: backend_php
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend
    depends_on:
      - db
      - redis_cache
    environment:
      - SYMFONY_ENV=dev
    networks:
      - services-net


  # Frontend Storefront (Next.js)
  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    container_name: storefront_app
    restart: unless-stopped
    ports:
      - "3010:3000"
    volumes:
      - ./storefront:/usr/src/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    networks:
      - services-net

  # Frontend Admin (Next.js)
  admin:
    build:
      context: ./admin-front
      dockerfile: Dockerfile
    container_name: admin_app
    restart: unless-stopped
    ports:
      - "3011:3000"
    volumes:
      - ./admin-front:/usr/src/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    networks:
      - services-net

  # Nginx Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - storefront
      - admin
      - backend
    volumes:
      - ./docker/nginx/virtualhosts:/etc/nginx/conf.d
      - ./backend:/var/www/backend
    networks:
      - services-net

volumes:
  db_data:
