export interface ConfAjustments {
    addonPayments: string;
    tireCalculator?: boolean;
    includeSitemap?: boolean;
    url: string;
    makeByDefault?: string;
    groupName: string;
    makes?:string;
    useConfigurator?:boolean;
    showMostVisitedCarBlock?:boolean;
    enableBasicHttpAuth?:boolean;
    basicHttpAuthUser?:string;
    basicHttpAuthPassword?:string;
    siteVideoId:number;
    onlyType?:boolean;
    whatsAppGroup?:string;
    googleAnalyticsCode?:string;
    googleAnalytics4Code?:string;
    googleTagManagerCode?:string;
    paypalId?:string;
    financialCalculator?:string;
    paypalReservationNewCar?:boolean;
    paypalReservationUsedCar?:boolean;
    siteWaterMark:string;
    callCenterManagment?:boolean;
    googleMapKey?:string;
    showRelatedCars?:boolean;
    enablePopup?: boolean;
    includeProdAnServInSitemap?: boolean;
    financedPriceBdVo?: boolean;
    financedPriceBdVn?: boolean;
    priceOnRequest?: boolean;
    emailReplayTo:string;
    emailReservationUserBrand:string;
    preferredBrandsWorkshopDate:string;
    redirectTabs:boolean;
    sendMailDealerStoreAdUser:boolean;
    listOrderUsedCars:number;
    listOrderNewCars:number;
    workshopDate:boolean;
    urlCitaTaller:string;
    urlBrads:string;
    workshopBrands:string;
    includeValuationSitemap:boolean;
    emailWorkshopDateBrands:string;
    emailRentingBrands:string;
    defaultLocale:string;
    locales:string;
    micrositeColor:string;
    
}