import { Role, UserRoles } from "@/types";

export const config = {
  defaultFilter: {},
  defaultPagination: { page: 1, perPage: 10 },
  defaultSort: { field: "createdAt", order: "DESC" },
  uniqueValues: true,
  tabs: [
    {
      name: "General",
      label: "General",
      columns: 2,
    },
  ],
  title: 'Usuarios',
  description: 'Gestión de usuarios',
  admin: 'dashboard',
  actions:['edit', 'view', 'add'],
  // Cualquier otra configuración que necesites
} as any;

export const Roles: Role[] = [
  { id: 1, value: UserRoles.SUPERADMIN, label: "Super Admin" },
  { id: 2, value: UserRoles.CAIXA, label: "Caixa"},
  { id: 3, value: UserRoles.ADMIN, label: "Admin" },
  { id: 4, value: UserRoles.DEALER, label: "Dealer" },
  { id: 5, value: UserRoles.SHOP, label: "Shop" },
  { id: 6, value: UserRoles.USER, label: "User" },
];

export const Item = [
  {
    name: "id",
    type: "id",
    label: "ID",
    inList: true,
    required: true,
    hide: true,
    column: 1,
    tab: "General",
  },
  {
    name: "id_mf",
    type: "id",
    label: "ID_MF",
    inList: true,
    required: true,
    hide: true,
    column: 1,
    sortable: true,
    inSearch: true,
    tab: "General",
  },
  {
    name: "dealerId",
    type: "select",
    label: "ID Dealer",
    selection: "single",
    inList: true,
    hide: false,
    column: 2,
    columns: 1,
    required: true,
    visible: true,
    sortable: true,
    inSearch: true,
    inFilter: true,
    options: [],
    tab: "General",
  },
  {
    name: "name",
    type: "text",
    label: "Nombre",
    required: true,
    inList: true,
    sortable: true,
    model: "users",
    inSearch: true,
    visible: true,
    column: 1,
    columns: 2,
    tab: "General",
  },
  {
    name: "user",
    type: "text",
    label: "Usuario",
    sortable: true,
    required: true,
    inList: true,
    inSearch: true,
    visible: true,
    column: 1,
    columns: 2,
    tab: "General",
  },
  {
    name: "email",
    type: "email",
    label: "Email",
    required: true,
    inList: true,
    inSearch: true,
    column: 1,
    tab: "General",
  },
  {
    name: "phone",
    type: "phone",
    label: "Teléfono",
    required: false,
    column: 1,
    tab: "General",
  },
  {
    name: "roles",
    type: "select",
    selection: "single",
    label: "Roles",
    required: true,
    inList: true,
    sortable: true,
    inFilter: true,
    visible: true,
    options: Roles,
    column: 2,
    tab: "General",
  },
  // {
  //   name: "dealer",
  //   type: "input",
  //   label: "Dealer",
  //   inList: true,
  //   options: [],
  //   column: 2,
  //   tab: "General",
  // },
  {
    name: "enabled",
    type: "boolean",
    label: "Activo",
    required: true,
    inList: true,
    sortable: true,
    inFilter: true,
    visible: true,
    column: 2,
    tab: "General",
    edit: false,
  },
  {
    name: "password",
    type: "password",
    label: "Contraseña",
    required: true,
    column: 2,
    tab: "General",
    visible: false,
    inList: false,
  },
  {
    name: "confirm_password",
    type: "confirm_password",
    label: "Confirmar contraseña",
    required: true,
    column: 2,
    tab: "General",
    inList: false,
  },
  {
    name: "createdAt",
    type: "date",
    label: "Fecha de creación",
    required: false,
    inList: true,
    sortable: false,
    inFilter: false,
    visible: false,
  },
  {
    name: "updatedAt",
    type: "date",
    label: "Última actualización",
    required: false,
    inList: true,
  },
];
